package cn.edu.bupt.yaoxintong.admin.pojo;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "medicine")
public class Medicine {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.id
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    @Id
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.drug_name
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String drugName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.brand
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.manufacturer
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String manufacturer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.license_number
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String licenseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.recommend
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String recommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.drug_form
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String drugForm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.type
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.drug_type_1
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String drugType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.drug_type_2
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String drugType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.drug_type_3
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String drugType3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.prescription_type
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String prescriptionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.import_type
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String importType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.drug_specifications
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String drugSpecifications;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.product_place
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String productPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.valid_period
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String validPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.use_for_illness
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String useForIllness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.use_for_people
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String useForPeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.use_function
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String useFunction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.dosage_use
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String dosageUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.Storage_condition
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String storageCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.product_weight
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String productWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.price
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medicine.hot
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private Integer hot;

    private Integer authentication;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.id
     *
     * @return the value of medicine.id
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.id
     *
     * @param id the value for medicine.id
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.drug_name
     *
     * @return the value of medicine.drug_name
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getDrugName() {
        return drugName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.drug_name
     *
     * @param drugName the value for medicine.drug_name
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setDrugName(String drugName) {
        this.drugName = drugName == null ? null : drugName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.brand
     *
     * @return the value of medicine.brand
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.brand
     *
     * @param brand the value for medicine.brand
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.manufacturer
     *
     * @return the value of medicine.manufacturer
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.manufacturer
     *
     * @param manufacturer the value for medicine.manufacturer
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer == null ? null : manufacturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.license_number
     *
     * @return the value of medicine.license_number
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getLicenseNumber() {
        return licenseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.license_number
     *
     * @param licenseNumber the value for medicine.license_number
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setLicenseNumber(String licenseNumber) {
        this.licenseNumber = licenseNumber == null ? null : licenseNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.recommend
     *
     * @return the value of medicine.recommend
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.recommend
     *
     * @param recommend the value for medicine.recommend
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setRecommend(String recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.drug_form
     *
     * @return the value of medicine.drug_form
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getDrugForm() {
        return drugForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.drug_form
     *
     * @param drugForm the value for medicine.drug_form
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setDrugForm(String drugForm) {
        this.drugForm = drugForm == null ? null : drugForm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.type
     *
     * @return the value of medicine.type
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.type
     *
     * @param type the value for medicine.type
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.drug_type_1
     *
     * @return the value of medicine.drug_type_1
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getDrugType1() {
        return drugType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.drug_type_1
     *
     * @param drugType1 the value for medicine.drug_type_1
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setDrugType1(String drugType1) {
        this.drugType1 = drugType1 == null ? null : drugType1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.drug_type_2
     *
     * @return the value of medicine.drug_type_2
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getDrugType2() {
        return drugType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.drug_type_2
     *
     * @param drugType2 the value for medicine.drug_type_2
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setDrugType2(String drugType2) {
        this.drugType2 = drugType2 == null ? null : drugType2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.drug_type_3
     *
     * @return the value of medicine.drug_type_3
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getDrugType3() {
        return drugType3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.drug_type_3
     *
     * @param drugType3 the value for medicine.drug_type_3
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setDrugType3(String drugType3) {
        this.drugType3 = drugType3 == null ? null : drugType3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.prescription_type
     *
     * @return the value of medicine.prescription_type
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getPrescriptionType() {
        return prescriptionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.prescription_type
     *
     * @param prescriptionType the value for medicine.prescription_type
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setPrescriptionType(String prescriptionType) {
        this.prescriptionType = prescriptionType == null ? null : prescriptionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.import_type
     *
     * @return the value of medicine.import_type
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getImportType() {
        return importType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.import_type
     *
     * @param importType the value for medicine.import_type
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setImportType(String importType) {
        this.importType = importType == null ? null : importType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.drug_specifications
     *
     * @return the value of medicine.drug_specifications
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getDrugSpecifications() {
        return drugSpecifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.drug_specifications
     *
     * @param drugSpecifications the value for medicine.drug_specifications
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setDrugSpecifications(String drugSpecifications) {
        this.drugSpecifications = drugSpecifications == null ? null : drugSpecifications.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.product_place
     *
     * @return the value of medicine.product_place
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getProductPlace() {
        return productPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.product_place
     *
     * @param productPlace the value for medicine.product_place
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setProductPlace(String productPlace) {
        this.productPlace = productPlace == null ? null : productPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.valid_period
     *
     * @return the value of medicine.valid_period
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getValidPeriod() {
        return validPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.valid_period
     *
     * @param validPeriod the value for medicine.valid_period
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setValidPeriod(String validPeriod) {
        this.validPeriod = validPeriod == null ? null : validPeriod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.use_for_illness
     *
     * @return the value of medicine.use_for_illness
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getUseForIllness() {
        return useForIllness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.use_for_illness
     *
     * @param useForIllness the value for medicine.use_for_illness
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setUseForIllness(String useForIllness) {
        this.useForIllness = useForIllness == null ? null : useForIllness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.use_for_people
     *
     * @return the value of medicine.use_for_people
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getUseForPeople() {
        return useForPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.use_for_people
     *
     * @param useForPeople the value for medicine.use_for_people
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setUseForPeople(String useForPeople) {
        this.useForPeople = useForPeople == null ? null : useForPeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.use_function
     *
     * @return the value of medicine.use_function
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getUseFunction() {
        return useFunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.use_function
     *
     * @param useFunction the value for medicine.use_function
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setUseFunction(String useFunction) {
        this.useFunction = useFunction == null ? null : useFunction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.dosage_use
     *
     * @return the value of medicine.dosage_use
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getDosageUse() {
        return dosageUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.dosage_use
     *
     * @param dosageUse the value for medicine.dosage_use
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setDosageUse(String dosageUse) {
        this.dosageUse = dosageUse == null ? null : dosageUse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.Storage_condition
     *
     * @return the value of medicine.Storage_condition
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getStorageCondition() {
        return storageCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.Storage_condition
     *
     * @param storageCondition the value for medicine.Storage_condition
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setStorageCondition(String storageCondition) {
        this.storageCondition = storageCondition == null ? null : storageCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.product_weight
     *
     * @return the value of medicine.product_weight
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getProductWeight() {
        return productWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.product_weight
     *
     * @param productWeight the value for medicine.product_weight
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setProductWeight(String productWeight) {
        this.productWeight = productWeight == null ? null : productWeight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.price
     *
     * @return the value of medicine.price
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.price
     *
     * @param price the value for medicine.price
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medicine.hot
     *
     * @return the value of medicine.hot
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public Integer getHot() {
        return hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.hot
     *
     * @param hot the value for medicine.hot
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setHot(Integer hot) {
        this.hot = hot;
    }

    public Integer getAuthentication() {
        return authentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medicine.hot
     *
     * @param hot the value for medicine.hot
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setAuthentication(Integer authentication) {
        this.authentication = authentication;
    }
}