package cn.edu.bupt.yaoxintong.admin.pojo;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;

@Entity
public class News {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.id
     *
     * @mbggenerated Mon Mar 19 21:07:29 CST 2018
     */
	@Id
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.content
     *
     * @mbggenerated Mon Mar 19 21:07:29 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.url
     *
     * @mbggenerated Mon Mar 19 21:07:29 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.img
     *
     * @mbggenerated Mon Mar 19 21:07:29 CST 2018
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.time
     *
     * @mbggenerated Mon Mar 19 21:07:29 CST 2018
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.id
     *
     * @return the value of news.id
     *
     * @mbggenerated Mon Mar 19 21:07:29 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.id
     *
     * @param id the value for news.id
     *
     * @mbggenerated Mon Mar 19 21:07:29 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.content
     *
     * @return the value of news.content
     *
     * @mbggenerated Mon Mar 19 21:07:29 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.content
     *
     * @param content the value for news.content
     *
     * @mbggenerated Mon Mar 19 21:07:29 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.url
     *
     * @return the value of news.url
     *
     * @mbggenerated Mon Mar 19 21:07:29 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.url
     *
     * @param url the value for news.url
     *
     * @mbggenerated Mon Mar 19 21:07:29 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.img
     *
     * @return the value of news.img
     *
     * @mbggenerated Mon Mar 19 21:07:29 CST 2018
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.img
     *
     * @param img the value for news.img
     *
     * @mbggenerated Mon Mar 19 21:07:29 CST 2018
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.time
     *
     * @return the value of news.time
     *
     * @mbggenerated Mon Mar 19 21:07:29 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.time
     *
     * @param time the value for news.time
     *
     * @mbggenerated Mon Mar 19 21:07:29 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }
}