package cn.edu.bupt.yaoxintong.admin.pojo;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
@Entity
@Table(name = "yaoxintong_business")
public class YaoxintongBusiness {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_business.id
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
	@Id
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_business.username
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_business.business_name
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    private String businessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_business.business_scope
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    private String businessScope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_business.business_type
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    private String businessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_business.contact
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_business.email
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_business.password
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_business.salt
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_business.sex
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_business.status
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_business.register_time
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    private Date registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_business.openid
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_business.sign
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_business.business_license
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    private String businessLicense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_business.address
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_business.details
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    private String details;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_business.id
     *
     * @return the value of yaoxintong_business.id
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_business.id
     *
     * @param id the value for yaoxintong_business.id
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_business.username
     *
     * @return the value of yaoxintong_business.username
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_business.username
     *
     * @param username the value for yaoxintong_business.username
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_business.business_name
     *
     * @return the value of yaoxintong_business.business_name
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_business.business_name
     *
     * @param businessName the value for yaoxintong_business.business_name
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public void setBusinessName(String businessName) {
        this.businessName = businessName == null ? null : businessName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_business.business_scope
     *
     * @return the value of yaoxintong_business.business_scope
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public String getBusinessScope() {
        return businessScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_business.business_scope
     *
     * @param businessScope the value for yaoxintong_business.business_scope
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public void setBusinessScope(String businessScope) {
        this.businessScope = businessScope == null ? null : businessScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_business.business_type
     *
     * @return the value of yaoxintong_business.business_type
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_business.business_type
     *
     * @param businessType the value for yaoxintong_business.business_type
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType == null ? null : businessType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_business.contact
     *
     * @return the value of yaoxintong_business.contact
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_business.contact
     *
     * @param contact the value for yaoxintong_business.contact
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_business.email
     *
     * @return the value of yaoxintong_business.email
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_business.email
     *
     * @param email the value for yaoxintong_business.email
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_business.password
     *
     * @return the value of yaoxintong_business.password
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_business.password
     *
     * @param password the value for yaoxintong_business.password
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_business.salt
     *
     * @return the value of yaoxintong_business.salt
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_business.salt
     *
     * @param salt the value for yaoxintong_business.salt
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_business.sex
     *
     * @return the value of yaoxintong_business.sex
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_business.sex
     *
     * @param sex the value for yaoxintong_business.sex
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_business.status
     *
     * @return the value of yaoxintong_business.status
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_business.status
     *
     * @param status the value for yaoxintong_business.status
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_business.register_time
     *
     * @return the value of yaoxintong_business.register_time
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_business.register_time
     *
     * @param registerTime the value for yaoxintong_business.register_time
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_business.openid
     *
     * @return the value of yaoxintong_business.openid
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_business.openid
     *
     * @param openid the value for yaoxintong_business.openid
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_business.sign
     *
     * @return the value of yaoxintong_business.sign
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_business.sign
     *
     * @param sign the value for yaoxintong_business.sign
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_business.business_license
     *
     * @return the value of yaoxintong_business.business_license
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public String getBusinessLicense() {
        return businessLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_business.business_license
     *
     * @param businessLicense the value for yaoxintong_business.business_license
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public void setBusinessLicense(String businessLicense) {
        this.businessLicense = businessLicense == null ? null : businessLicense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_business.address
     *
     * @return the value of yaoxintong_business.address
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_business.address
     *
     * @param address the value for yaoxintong_business.address
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_business.details
     *
     * @return the value of yaoxintong_business.details
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_business.details
     *
     * @param details the value for yaoxintong_business.details
     *
     * @mbggenerated Mon Mar 19 19:09:00 CST 2018
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }
}