package cn.edu.bupt.yaoxintong.admin.pojo;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
@Entity
@Table(name = "yaoxintong_admin")
public class YaoxintongAdmin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_admin.id
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
	@Id
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_admin.adminname
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String adminname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_admin.password
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_admin.salt
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_admin.type
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_admin.avatar
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_admin.registertime
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private Date registertime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_admin.id
     *
     * @return the value of yaoxintong_admin.id
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_admin.id
     *
     * @param id the value for yaoxintong_admin.id
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_admin.adminname
     *
     * @return the value of yaoxintong_admin.adminname
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getAdminname() {
        return adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_admin.adminname
     *
     * @param adminname the value for yaoxintong_admin.adminname
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setAdminname(String adminname) {
        this.adminname = adminname == null ? null : adminname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_admin.password
     *
     * @return the value of yaoxintong_admin.password
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_admin.password
     *
     * @param password the value for yaoxintong_admin.password
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_admin.salt
     *
     * @return the value of yaoxintong_admin.salt
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_admin.salt
     *
     * @param salt the value for yaoxintong_admin.salt
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_admin.type
     *
     * @return the value of yaoxintong_admin.type
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_admin.type
     *
     * @param type the value for yaoxintong_admin.type
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_admin.avatar
     *
     * @return the value of yaoxintong_admin.avatar
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_admin.avatar
     *
     * @param avatar the value for yaoxintong_admin.avatar
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_admin.registertime
     *
     * @return the value of yaoxintong_admin.registertime
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public Date getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_admin.registertime
     *
     * @param registertime the value for yaoxintong_admin.registertime
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setRegistertime(Date registertime) {
        this.registertime = registertime;
    }
}