package cn.edu.bupt.yaoxintong.admin.pojo;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
@Entity
@Table(name = "yaoxintong_user")
public class YaoxintongUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_user.id
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
	@Id
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_user.username
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_user.password
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_user.salt
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_user.birthday
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_user.sex
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_user.status
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_user.register_time
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private Date registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_user.openid
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_user.contact
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaoxintong_user.details
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    private String details;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_user.id
     *
     * @return the value of yaoxintong_user.id
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_user.id
     *
     * @param id the value for yaoxintong_user.id
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_user.username
     *
     * @return the value of yaoxintong_user.username
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_user.username
     *
     * @param username the value for yaoxintong_user.username
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_user.password
     *
     * @return the value of yaoxintong_user.password
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_user.password
     *
     * @param password the value for yaoxintong_user.password
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_user.salt
     *
     * @return the value of yaoxintong_user.salt
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_user.salt
     *
     * @param salt the value for yaoxintong_user.salt
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_user.birthday
     *
     * @return the value of yaoxintong_user.birthday
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_user.birthday
     *
     * @param birthday the value for yaoxintong_user.birthday
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_user.sex
     *
     * @return the value of yaoxintong_user.sex
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_user.sex
     *
     * @param sex the value for yaoxintong_user.sex
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_user.status
     *
     * @return the value of yaoxintong_user.status
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_user.status
     *
     * @param status the value for yaoxintong_user.status
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_user.register_time
     *
     * @return the value of yaoxintong_user.register_time
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_user.register_time
     *
     * @param registerTime the value for yaoxintong_user.register_time
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_user.openid
     *
     * @return the value of yaoxintong_user.openid
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_user.openid
     *
     * @param openid the value for yaoxintong_user.openid
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_user.contact
     *
     * @return the value of yaoxintong_user.contact
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_user.contact
     *
     * @param contact the value for yaoxintong_user.contact
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaoxintong_user.details
     *
     * @return the value of yaoxintong_user.details
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaoxintong_user.details
     *
     * @param details the value for yaoxintong_user.details
     *
     * @mbggenerated Sun Mar 18 22:43:31 CST 2018
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }
}